comp_name = input()
comp_address = input()
comp_phone = input()
comp_fax = input()
comp_website = input()
manager_name = input()
manager_surname = input()
manager_age = input()
manager_phone = input()
print(comp_name)
print(f'Address: {comp_address}')
print(f'Tel. {comp_phone}')
print(f'Fax: {comp_fax}')
print(f'Web site: {comp_website}')
print(f'Manager: {manager_name} {manager_surname} (age: {manager_age}, tel. {manager_phone})')

